// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package perso.stealthnet.webcache

case class AddPeer(port: Int)


case class AddPeerResponse()


case class GetPeer()


case class GetPeerResponse(GetPeerResult: Option[String] = None)


case class RemovePeer()


case class RemovePeerResponse()

