// Generated by <a href="http://scalaxb.org/">scalaxb</a>.
package perso.stealthnet.webcache

trait RshareSoap {
  def addPeer(port: Int): Either[scalaxb.Fault[Any], perso.stealthnet.webcache.AddPeerResponse]
  def getPeer(): Either[scalaxb.Fault[Any], perso.stealthnet.webcache.GetPeerResponse]
  def removePeer(): Either[scalaxb.Fault[Any], perso.stealthnet.webcache.RemovePeerResponse]
}




